### ISSUE TITLE
Package not working on all website

### ISSUE THREAD

**Issue by vtibo** [shweshi/OpenGraph#29]
The package seems not to work with some website.
for exemple this one :
https://www.udemy.com/formation-a-la-photographie-pour-les-debutants/

I tried with other package and it seems to be a 403 error ...
any clue on this ?

**Comment by shweshi** [comment]
Hi @vtibo thanks for pointing this out. I tried with the same URL. Looks like this URL as well as some other urls doesn't allow the scripts to fetch the data. The fix is to add the user-agent in the request headers. This issue is now fixed.

**Comment by shweshi** [comment]
Fixed in PR #31

**Comment by vtibo** [comment]
Big THX @shweshi
