### ISSUE TITLE
Unable to retrieve og data for FB posts 

### ISSUE THREAD

**Issue by Yashaswini** [shweshi/OpenGraph#34]
Hi Team, 
Before I speak about the issue, I would first like to say that the package does a very good job on almost all urls. Great job !

To speak about the issue I am facing, am having troubles only with retrieving og data for FB posts url.  The result appears empty. 
However this is not the case when I use this package with twiiter urls, blogs, instagram urls. 
So I am here to seek some help in case am missing something in the way am accessing it. 

TIA

**Comment by shweshi** [comment]
@Yashaswini Thanks for using the package. If possible can you please share the example url that you are trying to fetch the OG data. So that I can help you.

**Comment by shweshi** [comment]
Here is what you can try..

1. Check if the url is valid
2. Check if the url is publicly accessible
3. Check if url doesnt need login with FB
4. Verify FB post is not private.

**Comment by Yashaswini** [comment]
Hi, 
Thanks for your inputs. However, when I access the same Fb post URL(which you have mentioned) in my application using fetch() method it results in an empty result. I wonder what is going wrong. 

TIA

**Comment by shweshi** [comment]
@Yashaswini  check the package of the version and make sure it's latest 1.0.6 and it would be helpful if you can provide code snippet to further debug the issue.

**Comment by shweshi** [comment]
No Response. Closing this issue.

**Comment by NetRally** [comment]
Same issue here too. After some query try Fb need login for public contents too
https://laravelopengraph.herokuapp.com/api/fetch?url=https://fb.watch/5nsZv_5BmC/

**Comment by shweshi** [comment]
@NetRally For me, it's working and returning the data. Is it possible to share how are you trying to fetch it?
![Screenshot from 2021-05-10 00-36-15](https://user-images.githubusercontent.com/35127382/117583963-c6146b80-b127-11eb-8055-747095f05d59.png)

**Comment by NetRally** [comment]
Worked me too at the begining but after a fourth query - mixed urls also, not only the same - the fb response:
{"site_name":"Facebook","url":"https:\/\/www.facebook.com\/login\/?next=https%3A%2F%2Fwww.facebook.com%2Fwatch%2F%3Fv%3D2308925129416683","locale":"en_US","locale:alternate":"ja_JP"}
Happened the same on my server too. I know it is fb limitation and after still unknown time release the lock
