### ISSUE TITLE
throwing an exception when the url returns 404 -breaking test.

### ISSUE THREAD

**Issue by jayenne** [shweshi/OpenGraph#67]
**Describe the bug**

**To Reproduce**
Run a test from cli that calls...
```$data = OpenGraph::fetch($url, true); // where url returns a 404 error.```
See error: ```shweshi\OpenGraph\Exceptions\FetchException. The requested URL returned error: 404 Not Found```

**Expected behavior**
I would have expected the error to have been failed gracefully, returning the 404 message to the calling method.

**Desktop (please complete the following information):**
 - OS: MacOS with Docker/Laradock
 - Browser n/a
 - Version current/latest

**Additional context**
I'm actually calling it with... but still not getting past the fetch error thrown.
```php
try {
            $data = OpenGraph::fetch($url, true);
        } catch (shweshi\OpenGraph\Exceptions\FetchException $e) {
            $message = $e->getMessage();
            $data = $e->getData();
        }
```

**Comment by RageZBla** [comment]
Hello, may I work on this issue?
