### ISSUE TITLE
Add support for Laravel 11

### ISSUE THREAD

**Issue by pilutiful** [shweshi/OpenGraph#91]
First thank you for this package! it helps me a lot. I tried upgrading my Laravel project to 11 (from 10), but it seems this package is not compatible with the new Laravel.
When I try running composer update I get following:

  Problem 1
    - shweshi/opengraph V1.1.3 requires illuminate/log ^5.0|^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by illuminate/log[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.1].
    - shweshi/opengraph[V1.1.1, ..., V1.1.2] require illuminate/log ^5.0|^6.0|^7.0|^8.0|^9.0 -> satisfiable by illuminate/log[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16].
    - shweshi/opengraph V1.1.0 requires illuminate/log ^5.0|^6.0|^7.0|^8.0 -> satisfiable by illuminate/log[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27].
    - Only one of these can be installed: illuminate/log[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.1], laravel/framework[v11.0.0]. laravel/framework replaces illuminate/log and thus cannot coexist with it.
    - illuminate/log[v5.6.0, ..., v5.8.36] require php ^7.1.3 -> your php version (8.3.3) does not satisfy that requirement.
    - illuminate/log[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.3.3) does not satisfy that requirement.
    - illuminate/log[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.3.3) does not satisfy that requirement.
    - illuminate/log[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.3.3) does not satisfy that requirement.
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0].
    - Root composer.json requires shweshi/opengraph ^1.1 -> satisfiable by shweshi/opengraph[V1.1.0, V1.1.1, V1.1.2, V1.1.3].

It would be amazing if this was possible.

**Comment by weogrim** [comment]
@shweshi is support for Laravel 11 is possible ?

**Comment by shweshi** [comment]
Laravel support is added. @pilutiful @weogrim
